### ISSUE TITLE
Tests needed for Python interop/compatibility

### ISSUE THREAD

**Issue by sehe** [karkason/cppystruct#8]
I notice the tests don't seem to verify binary compatibility with the Python pendants.

I expected this to be the core purpose of the library, so it would definitely need to be in the tests (before coverage, e.g.). Alternatively, if the goal of the library is **not** binary compatibility or interoperability with python, that should be made very clear in the documentation.

**Comment by karkason** [comment]
I agree! 
How would you go around testing for binary compatibility? Invoking a python script for every test case and comparing the results?
